#!/bin/sh

sudo pkill -f bgio.sh

pushd ..
go clean
go build -mod=vendor
popd

./bgio.sh &
PID="$!"
echo "PID: $PID"
../chill -p $PID

echo 'Sleeping for 5 seconds before reprioritizing background I/O'
sleep 5
sudo ../chill -c best-effort -n 3 -p $PID
../chill -p $PID

echo 'Sleeping for 5 seconds before reprioritizing background I/O'
sleep 5
sudo ../chill -c 3 -p $PID
../chill -p $PID

echo 'Running for 5 seconds before killing background I/O'
sleep 5
kill "$PID"
rm -rf _testdir
